FROM python:3.8-slim-buster

LABEL MAINTAINER="FirstName LastName <example@domain.com>"

WORKDIR /var/www/

ADD . /var/www/

RUN pip3 install -r requirements.txt

ARG APP_PORT

EXPOSE $APP_PORT

# CMD [ "gunicorn", "-w", "4", "--bind", "0.0.0.0${APP_PORT}", "app:app"]
CMD ["python3", "app.py"]